### ISSUE TITLE
Notebooks

### ISSUE THREAD

**Issue by tpoisot** [EcoJulia/EcoJulia.github.io#1]
To avoid saturating the git history with notebooks, what about the following workflow?

1. documents written as Jmd
2. compiled with Weave to a md file + images
3. exported as a notebook that can be downloaded, but is not pre-executed

**Comment by mkborregaard** [comment]
I don't see anything wrong with the approach, but is it a problem with a big git history here? I wouldn't expect many people to clone the repo (unless there is some detail I am not aware of?).
